### ISSUE TITLE
mgmt_interface

### ISSUE THREAD

**Issue by Aramideh** [boogert-lab/MapMarkers#1]
Hi,
I loaded the module in the application and put the required module definition xml parts in config.xml and gui.xml. when clicking on "Activate Configuration Interface", I'm getting the attached error.

[mgmt_interface.txt](https://github.com/boogert-lab/MapMarkers/files/5028190/mgmt_interface.txt)

**Comment by boogert-lab** [comment]
Thanks for reporting. I will look into this soon.

With kind regards,

André





André van den Boogert

Senior Consultant


Realworld Software Products BV

Venusstraat 17
4105 JH  Culemborg
Netherlands


+31611450790

+31345614406

andre.van.den.boogert@realworld-systems.com

www.realworld-systems.com<http://www.realworld-systems.com>

<https://www.youtube.com/user/realworld2all>    <https://twitter.com/realworldtweets>   <https://www.linkedin.com/company/41216>        <https://www.facebook.com/realworldsystems>

________________________________

**Comment by Aramideh** [comment]
This one was caused by a package issue, in the  raster_symbol_manager_gui exemplar there wasn't a package sw statement, while calling l_d << raster_symbol_manager_gui.new_dialog(l_app,raster_symbol_handler,_self) it is looking for raster_symbol_manager in the user package and causing the error.
fixed it with l_d << sw:raster_symbol_manager_gui.new_dialog(l_app,raster_symbol_handler,_self) and declaring package sw in the raster_symbol_manager_gui exemplar.

**Comment by boogert-lab** [comment]
The file I see : mapmarkers\raster_symbols\modules\core\raster_symbols_gui\source\raster_symbol_manager_gui.magik does have a package statement.

**Comment by Aramideh** [comment]
Yes Indeed. Thank You.
