### ISSUE TITLE
missing slot on simple_grid

### ISSUE THREAD

**Issue by Aramideh** [boogert-lab/MapMarkers#2]
simple_grid class in core 4.3.0 doesn't have a slot named "cached_image", which is causing an error on "..\MapMarkers\raster_symbols\modules\core\raster_symbols_core\source\sw\extras\simple_grid_extras.magik".
I commented the .cached_image << _unset line so I could load the module.

**Comment by boogert-lab** [comment]
Hi,

Mapmarkers is intended to be used in Smallworld 5.

With kind regards,

André





André van den Boogert

Senior Consultant


Realworld Software Products BV

Venusstraat 17
4105 JH  Culemborg
Netherlands


+31611450790

+31345614406

andre.van.den.boogert@realworld-systems.com

www.realworld-systems.com<http://www.realworld-systems.com>

<https://www.youtube.com/user/realworld2all>    <https://twitter.com/realworldtweets>   <https://www.linkedin.com/company/41216>        <https://www.facebook.com/realworldsystems>

________________________________

**Comment by Aramideh** [comment]
Thank You Sir,

maybe some changes to the documentation then :-) "The software will work from 4.3.0 and is lately tested on 5.2.2.".

https://cavdb186.home.xs4all.nl/mapmarkers/help/index.html

**Comment by boogert-lab** [comment]
Yes, you are right. Sorry about that.

With kind regards,

André





André van den Boogert

Senior Consultant


Realworld Software Products BV

Venusstraat 17
4105 JH  Culemborg
Netherlands


+31611450790

+31345614406

andre.van.den.boogert@realworld-systems.com

www.realworld-systems.com<http://www.realworld-systems.com>

<https://www.youtube.com/user/realworld2all>    <https://twitter.com/realworldtweets>   <https://www.linkedin.com/company/41216>        <https://www.facebook.com/realworldsystems>

________________________________
