### ISSUE TITLE
raster_symbol_selector error

### ISSUE THREAD

**Issue by Aramideh** [boogert-lab/MapMarkers#3]
while loading the class "raster_symbol_selector", I encountered the below error.

**** Error: Index 2 out of bounds
     index_out_of_bounds(index=2)

---- traceback: events (heavy_thread 2709042) ----
time=05/08/2020 16:47:55
sw!version=4.3.0.2 (swaf)
os_text_encoding=cp1252
!snapshot_traceback?!=True

[1] condition(information).raise(:index_out_of_bounds, {:index, 2})
[2] simple_vector:[1-1].out_of_bounds({2})
[3] simple_vector:[1-1].key_not_found({2})
[4] simple_vector:[1-1][2]
[5]     simple_vector:[1-5].fast_elements()
[6]   simple_vector:[1-5].elements()

fixed it with adding unset for ok_selector in the exemplar definition.
def_slotted_exemplar(:raster_symbol_selector,
	{
		{:ok_selector , _unset },
		{:items,_unset},
		{:current_selection,_unset},
		{:list,_unset},
		{:handler,_unset}
	},:model)
$

**Comment by boogert-lab** [comment]
Hi Sadeq,

Thanks for reporting this error. I will soon have a look at it.

With kind regards,

André





André van den Boogert

Senior Consultant


Realworld Software Products BV

Venusstraat 17
4105 JH  Culemborg
Netherlands


+31611450790

+31345614406

andre.van.den.boogert@realworld-systems.com

www.realworld-systems.com<http://www.realworld-systems.com>

<https://www.youtube.com/user/realworld2all>    <https://twitter.com/realworldtweets>   <https://www.linkedin.com/company/41216>        <https://www.facebook.com/realworldsystems>

________________________________

**Comment by boogert-lab** [comment]
This component needs swift. Maybe that causes the error?
